
version: '3.7'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  react:
    build:
      context: ./client
    volumes:
      - './client:/app'
      - './client/app/node_modules'