version: '3.7'

services:
  nginx:
    ports: 
      - "80:80"
    volumes:
      - ./nginx/build.conf:/etc/nginx/conf.d/default.conf:ro

  react:
    build:
      dockerfile: Dockerfile.prod
    # If image exists on docker-hob, allows docker-compose build from image
    image: aintone/create-react-app-template
