
version: '3.7'

services:

  react:
    container_name: react
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - './client/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true