
version: '3.7'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports: 
      - "3000:80"

  react:
    container_name: react
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/app'
      - './client/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true